language: python
python:
  - 3.6
  - 3.7
  - 3.8
script:
  - black --check openslides_write_service/ start.py
  - isort --check --recursive openslides_write_service/ start.py
  - mypy openslides_write_service/ start.py
